// <auto-generated />
using System;
using AppDataBaseView.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDataBaseView.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AppDataBaseView.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_code");

                    b.Property<string>("Addres")
                        .HasColumnType("TEXT")
                        .HasColumnName("addres");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("Fcs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fcs");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("passport");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("phonenumber");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.HasKey("EmployeeCode");

                    b.HasIndex(new[] { "Passport" }, "IX_Employees_passport")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Flight", b =>
                {
                    b.Property<int>("FlightCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("flight_code");

                    b.Property<DateTime>("AriveData")
                        .HasColumnType("TEXT")
                        .HasColumnName("arive_data");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("customer");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_code");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("_from");

                    b.Property<string>("IsBought")
                        .HasColumnType("BOOL")
                        .HasColumnName("is_bought");

                    b.Property<string>("IsRefund")
                        .HasColumnType("BOOL")
                        .HasColumnName("is_refund");

                    b.Property<int>("LoadCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("load_code");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("DECIMAL")
                        .HasColumnName("price");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("send_date");

                    b.Property<string>("Where")
                        .IsRequired()
                        .HasColumnType("TEX")
                        .HasColumnName("_where");

                    b.HasKey("FlightCode");

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("LoadCode");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Load", b =>
                {
                    b.Property<int>("LoadCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("load_code");

                    b.Property<string>("Describe")
                        .HasColumnType("TEXT")
                        .HasColumnName("describe");

                    b.Property<string>("ExpDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exp_date");

                    b.Property<int>("LoadTypeCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("load_type_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("LoadCode");

                    b.HasIndex("LoadTypeCode");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("AppDataBaseView.Models.TypesAuto", b =>
                {
                    b.Property<int>("AutoTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_type_code");

                    b.Property<string>("Describe")
                        .HasColumnType("TEXT")
                        .HasColumnName("describe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("AutoTypeCode");

                    b.ToTable("TypesAuto", (string)null);
                });

            modelBuilder.Entity("AppDataBaseView.Models.TypesLoad", b =>
                {
                    b.Property<int>("LoadTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("load_type_code");

                    b.Property<int>("AutoTypeCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_type_code");

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("describe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("LoadTypeCode");

                    b.HasIndex("AutoTypeCode");

                    b.ToTable("TypesLoads");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Flight", b =>
                {
                    b.HasOne("AppDataBaseView.Models.Employee", "EmployeeCodeNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("EmployeeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDataBaseView.Models.Load", "LoadCodeNavigation")
                        .WithMany("Flights")
                        .HasForeignKey("LoadCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeCodeNavigation");

                    b.Navigation("LoadCodeNavigation");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Load", b =>
                {
                    b.HasOne("AppDataBaseView.Models.TypesLoad", "LoadTypeCodeNavigation")
                        .WithMany("Loads")
                        .HasForeignKey("LoadTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadTypeCodeNavigation");
                });

            modelBuilder.Entity("AppDataBaseView.Models.TypesLoad", b =>
                {
                    b.HasOne("AppDataBaseView.Models.TypesAuto", "AutoTypeCodeNavigation")
                        .WithMany("TypesLoads")
                        .HasForeignKey("AutoTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutoTypeCodeNavigation");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Employee", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AppDataBaseView.Models.Load", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AppDataBaseView.Models.TypesAuto", b =>
                {
                    b.Navigation("TypesLoads");
                });

            modelBuilder.Entity("AppDataBaseView.Models.TypesLoad", b =>
                {
                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
